default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['DB_POOL'] || ENV['RAILS_MAX_THREADS'] || 5 %>
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: talent-api_development

test:
  <<: *default
  database: talent-api_test
